-- Gemeinsamer Produktkatalog, dient auch als Cache für Open Food Facts
CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    barcode     VARCHAR(32) UNIQUE,
    category    VARCHAR(60),
    image_url   VARCHAR(500),
    nutri_score VARCHAR(1),
    source      VARCHAR(20)  NOT NULL CHECK (source IN ('MANUAL', 'OPEN_FOOD_FACTS'))
);
