-- Einträge der Einkaufsliste (Spalte owner kommt erst in Phase 2 per neuer Migration)
Create Table list_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INTEGER NOT NULL CHECK(quantity >= 1 AND quantity <= 99),
    checked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    product_id BIGINT NOT NULL REFERENCES product(id)
);