-- Nutzer. password_hash ist NULL bei Seed- und Sandbox-Nutzern, die sich nicht per Passwort anmelden
CREATE TABLE app_user
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR(40)              NOT NULL UNIQUE,
    password_hash      VARCHAR(100),
    display_name       VARCHAR(40)              NOT NULL,
    household_size     INTEGER                  NOT NULL CHECK (household_size BETWEEN 1 AND 6),
    leaderboard_opt_in BOOLEAN                  NOT NULL DEFAULT FALSE,
    sandbox            BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Einträge aus Phase 1 haben keinen Besitzer. Es sind nur Testdaten (E8), deshalb löschen.
DELETE FROM list_item;

-- ON DELETE CASCADE: Wird ein Nutzer gelöscht (z. B. alte Sandbox-Nutzer), verschwinden seine Daten mit
ALTER TABLE list_item
    ADD COLUMN owner_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE;

CREATE INDEX idx_list_item_owner ON list_item (owner_id);
