-- Läden des Nutzers
CREATE TABLE store
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    name     VARCHAR(60) NOT NULL,
    UNIQUE (owner_id, name)
);

-- Monatsbudget, year_month im Format 2026-10
CREATE TABLE monthly_budget
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT        NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    year_month VARCHAR(7)    NOT NULL,
    amount     NUMERIC(8, 2) NOT NULL CHECK (amount >= 1),
    UNIQUE (owner_id, year_month)
);

-- Abgeschlossener Einkauf
CREATE TABLE purchase
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id      BIGINT        NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    store_id      BIGINT        NOT NULL REFERENCES store (id),
    purchase_date DATE          NOT NULL,
    total_amount  NUMERIC(8, 2) NOT NULL CHECK (total_amount BETWEEN 0.01 AND 1000)
);

CREATE INDEX idx_purchase_owner_date ON purchase (owner_id, purchase_date);

-- Positionen eines Einkaufs (@ElementCollection in Purchase)
CREATE TABLE purchase_line
(
    purchase_id BIGINT  NOT NULL REFERENCES purchase (id) ON DELETE CASCADE,
    product_id  BIGINT  NOT NULL REFERENCES product (id),
    quantity    INTEGER NOT NULL CHECK (quantity >= 1)
);

-- Vorrat
CREATE TABLE pantry_item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT                   NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    product_id  BIGINT                   NOT NULL REFERENCES product (id),
    quantity    INTEGER                  NOT NULL CHECK (quantity >= 1),
    best_before DATE,
    added_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_pantry_item_owner ON pantry_item (owner_id);

-- Gewohnheiten (vorerst nur lesend)
CREATE TABLE habit
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id      BIGINT  NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    product_id    BIGINT  NOT NULL REFERENCES product (id),
    quantity      INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 99),
    interval_days INTEGER NOT NULL CHECK (interval_days >= 1),
    next_due      DATE    NOT NULL
);

CREATE INDEX idx_habit_owner ON habit (owner_id);

-- Monatliche Schlusskurse der ETFs (Kurs-Cache)
CREATE TABLE price_point
(
    symbol VARCHAR(10)    NOT NULL,
    month  VARCHAR(7)     NOT NULL,
    close  NUMERIC(12, 4) NOT NULL CHECK (close > 0),
    PRIMARY KEY (symbol, month)
);
